[package]
name = "SingleDice"
version = "0.0.1"
published-at = "0xaf05fd9b0a196ee214721b0894f854f6a3c4735a0a6bf3e45f6a827e7766ce37"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
dice = "0xaf05fd9b0a196ee214721b0894f854f6a3c4735a0a6bf3e45f6a827e7766ce37"
dice_test = "0x0"
